[package]
name = "rusty-os"
version = "0.0.1"
authors = ["David Angell <davidjangell42@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.8"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
